from __future__ import annotations

from dataclasses import asdict, dataclass
from pathlib import Path

from .diagnostics import diagnose_target
from .project_model import KeilTargetModel
from .tool_finder import find_arm_gcc_root, find_armclang_tools


@dataclass(slots=True)
class BackendOption:
    """单个后端的适配结论。

    `status` 表示当前阶段能不能直接采用，`score` 只用于排序，不代表绝对质量。
    这里刻意把“技术上更适合”和“本机工具已安装”拆开描述，避免把 ArmClang 这类
    兼容性路线误判成已经可以完整生成/构建的 GCC 路线。
    """

    backend: str
    status: str
    score: int
    title: str
    reasons: list[str]
    blockers: list[str]
    next_step: str


@dataclass(slots=True)
class BackendRecommendation:
    """后端推荐总结果。

    这是 KeilBridge 后续工作流的入口诊断：第一次创建 `.keilbridge` 前先跑它，
    再根据用户显式选择的 `--backend` 生成对应工作区。这样即使以后支持 ArmClang、
    Keil CLI 或 Debug-only，也不会污染当前已经验证过的 GCC 生成链路。
    """

    target: str
    recommended: str
    options: list[BackendOption]

    def to_dict(self) -> dict:
        return {
            "schema": "keilbridge.backend_recommendation.v1",
            "target": self.target,
            "recommended": self.recommended,
            "options": [asdict(item) for item in self.options],
        }


def recommend_backends(target: KeilTargetModel, armclang_root: str | None = None, arm_gcc_root: str | None = None) -> BackendRecommendation:
    """根据 Keil 工程事实推荐后端。

    推荐逻辑只基于工程结构、诊断项和本机工具链探测，不修改任何用户文件。
    它的目标不是给出“唯一正确答案”，而是把 GCC/ArmClang/Debug-only 的适配边界
    摆到用户面前，后续由用户选择明确的构建路线。
    """

    diagnostics = diagnose_target(target)
    diag_codes = {item.code for item in diagnostics}
    options = [
        _gcc_option(target, diag_codes, arm_gcc_root),
        _armclang_option(target, diag_codes, armclang_root),
        _debug_only_option(target),
        _keil_cli_option(target, diag_codes),
    ]
    ranked = sorted(options, key=lambda item: item.score, reverse=True)
    recommended = next((item.backend for item in ranked if item.status in {"ready", "candidate", "possible_after_fixes"}), ranked[0].backend)
    # 输出时把推荐项放到第一位，避免出现“recommended=gcc，但列表第一项是 ArmClang
    # candidate_tool_missing”的阅读歧义；score 仍保留在报告里用于解释排序背景。
    ordered = sorted(ranked, key=lambda item: (item.backend != recommended, -item.score))
    return BackendRecommendation(target=target.name, recommended=recommended, options=ordered)


def render_backend_recommendation_markdown(result: BackendRecommendation, target: KeilTargetModel) -> str:
    lines = [
        "# KeilBridge Backend Recommendation",
        "",
        f"- Target: `{target.name}`",
        f"- Device: `{target.device or 'unknown'}`",
        f"- Framework: `{target.features.framework}`",
        f"- Generated by: `{target.features.generated_by or 'unknown'}`",
        f"- RTOS: `{', '.join(target.features.rtos) if target.features.rtos else 'none detected'}`",
        f"- Recommended backend: `{result.recommended}`",
        "",
        "## Options",
        "",
    ]
    for option in result.options:
        lines.extend(
            [
                f"### {option.backend}",
                "",
                f"- Status: `{option.status}`",
                f"- Score: `{option.score}`",
                f"- Summary: {option.title}",
                "",
                "Reasons:",
            ]
        )
        lines.extend([f"- {item}" for item in option.reasons] or ["- No positive evidence."])
        lines.append("")
        lines.append("Blockers:")
        lines.extend([f"- {item}" for item in option.blockers] or ["- No blocking issue detected."])
        lines.extend(["", f"Next step: {option.next_step}", ""])
    return "\n".join(lines).rstrip() + "\n"


def _gcc_option(target: KeilTargetModel, diag_codes: set[str], arm_gcc_root: str | None) -> BackendOption:
    reasons = ["GCC 后端已经具备 CMake、GNU ld、GCC startup、OpenOCD/VS Code 生成链路。"]
    blockers: list[str] = []
    score = 70
    status = "ready"

    if find_arm_gcc_root(arm_gcc_root) or _tool_in_path("arm-none-eabi-gcc.exe"):
        reasons.append("本机检测到 Arm GNU Toolchain 或可通过 PATH 调用。")
        score += 10
    else:
        blockers.append("未检测到 Arm GNU Toolchain；需要安装或通过 --arm-gcc-root 指定。")
        status = "blocked"
        score -= 50

    if target.device_info.matched or target.memory:
        reasons.append("已能获得目标芯片内存布局，可生成 GNU ld 链接脚本。")
        score += 10
    else:
        blockers.append("无法确定芯片内存布局，GCC 链接脚本无法可靠生成。")
        status = "blocked"
        score -= 40

    if target.features.generated_by == "stm32cubemx":
        reasons.append("CubeMX 工程可复用 Core/Drivers/Middlewares，不需要改动 .ioc。")
        score += 5

    if "armcc_library" in diag_codes:
        blockers.append("检测到 ARMCC/Keil .lib；GCC 不能保证链接，需要 GCC 版库、源码库或兼容覆盖策略。")
        if status != "blocked":
            status = "possible_after_fixes"
        score -= 20

    if "startup_may_be_armasm" in diag_codes:
        reasons.append("Keil ARMASM startup 将由生成层替换为 GCC startup，原工程不动。")

    if "rtos_detected" in diag_codes:
        reasons.append("RTOS 工程需要确认 GCC portable 层和异常入口映射，当前只视为需验证项。")
        score -= 5

    if any(source.path.lower().endswith((".cpp", ".cxx", ".cc")) for source in target.sources):
        reasons.append("工程包含 C++，需要 ELF Doctor 检查 init_array 和全局构造；当前 GCC 链路已覆盖此类问题。")

    title = "适合作为开放构建和调试主路线。"
    next_step = "运行 configure --backend gcc，再 build、doctor elf、flash/debug。"
    return BackendOption("gcc", status, score, title, reasons, blockers, next_step)


def _armclang_option(target: KeilTargetModel, diag_codes: set[str], armclang_root: str | None) -> BackendOption:
    reasons = ["ArmClang 后端适合承接 Keil/AC6 生态中的 scatter、ARMASM startup 和部分 Keil 库依赖。"]
    blockers: list[str] = []
    score = 55
    tools = find_armclang_tools(armclang_root)
    missing = [name for name, path in tools.items() if not path]

    if not missing:
        reasons.append("本机检测到 armclang/armlink/armasm/fromelf。")
        score += 15
    else:
        blockers.append(f"本机 ArmClang 工具不完整，缺少：{', '.join(missing)}。")
        score -= 15

    if target.scatter_file or target.scatter_candidates:
        reasons.append("工程存在 scatter 信息，适合 ArmLink 路线复用或生成等价 scatter。")
        score += 10
    else:
        blockers.append("未发现 scatter 文件；ArmClang 路线需要从 Cpu/device 内存生成 scatter。")
        score -= 5

    if "armcc_library" in diag_codes:
        reasons.append("检测到 ARMCC/Keil .lib，ArmClang/Keil 兼容路线通常比 GCC 更有机会保留闭源库。")
        score += 15

    if "startup_may_be_armasm" in diag_codes:
        reasons.append("检测到 ARMASM 风格 startup，ArmClang 路线更接近原 Keil 工程语义。")
        score += 10

    if target.features.rtos:
        reasons.append("RTOS 工程可优先保留 Keil/ArmClang portable 层，减少 GCC port 迁移风险。")
        score += 5

    status = "candidate"
    if missing:
        status = "candidate_tool_missing"
    title = "适合作为高兼容迁移路线，但当前仍处于后端实现阶段。"
    next_step = "先补齐 ArmClang 工具链并运行 doctor backend；后续使用 configure --backend armclang 生成 ArmClang 工作区。"
    return BackendOption("armclang", status, score, title, reasons, blockers, next_step)


def _debug_only_option(target: KeilTargetModel) -> BackendOption:
    reasons = [
        "Debug-only 不负责重建固件，只负责加载 ELF/符号、连接 OpenOCD 或 GDB Server。",
        "当工程存在闭源库、复杂链接脚本或暂时无法离开 Keil 编译时，它可以作为保底调试路线。",
    ]
    blockers: list[str] = []
    score = 35
    if target.libraries:
        score += 5
    return BackendOption(
        "debug-only",
        "fallback",
        score,
        "适合作为构建受阻时的调试保底路线。",
        reasons,
        blockers,
        "使用 Keil 或原有链路生成 ELF，再让 KeilBridge 生成调试配置并运行 Flash/Debug Doctor。",
    )


def _keil_cli_option(target: KeilTargetModel, diag_codes: set[str]) -> BackendOption:
    reasons = [
        "Keil CLI 后端保留原 MDK 构建语义，适合闭源库、复杂 scatter 或厂商包强绑定项目。",
        "它不是跨平台开放构建路线，但可以作为真实交付项目的兼容兜底。",
    ]
    score = 30
    if "armcc_library" in diag_codes:
        score += 20
    if target.scatter_file:
        score += 5
    return BackendOption(
        "keil-cli",
        "fallback",
        score,
        "适合作为无法迁出 Keil 时的兼容兜底。",
        reasons,
        [],
        "保留 Keil 编译，KeilBridge 负责诊断、调试配置和后续自动化。",
    )


def _tool_in_path(name: str) -> bool:
    return any((Path(path) / name).exists() for path in __import__("os").environ.get("PATH", "").split(__import__("os").pathsep))
