from __future__ import annotations

import argparse
import json
import os
import subprocess
from dataclasses import asdict
from pathlib import Path

from .core.armclang_workspace import configure_armclang_workspace
from .core.backend_recommender import recommend_backends, render_backend_recommendation_markdown
from .core.diagnostics import diagnose_target
from .core.doctor import render_flash_doctor_markdown, run_flash_doctor
from .core.debug_only_workspace import configure_debug_only_workspace
from .core.elf_doctor import render_elf_doctor_markdown, run_elf_doctor
from .core.keil_parser import parse_uvprojx
from .core.keil_cli import run_keil_cli
from .core.openocd_target_resolver import resolve_openocd_target
from .core.openocd_backend import FlashRequest, OpenOcdConfig, parse_address, run_flash
from .core.scatter import generate_gnu_ld, parse_scatter_memory
from .core.tool_finder import armclang_environment, find_arm_gcc_root, find_armclang_tools, find_cmake, find_ninja, find_openocd, find_openocd_scripts
from .core.workspace import configure_workspace


def _pick_target(model, target_name: str | None):
    """选择 Keil Target。

    不指定 target 时沿用 Keil 文件中的第一个 Target，后续可以改成读取 uvoptx
    的当前活动 target。
    """

    if not model.targets:
        raise SystemExit("No targets found in Keil project.")
    if target_name is None:
        return model.targets[0]
    for target in model.targets:
        if target.name == target_name:
            return target
    names = ", ".join(target.name for target in model.targets)
    raise SystemExit(f"Target not found: {target_name}. Available targets: {names}")


def _sanitize_name(name: str) -> str:
    """把 Keil Target 名转换成可作为文件名/CMake 目标名的稳定名称。

    Keil Target 允许空格、横杠等字符，但 KeilBridge 生成的 ELF、OpenOCD 配置和
    linker/startup 文件都使用同一个规范化名称。这里必须和 generator/workspace 层
    保持一致，否则 `configure` 生成的文件名与 `flash` 查找的文件名会对不上。
    """

    return "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in name)


def _resolve_probe(target, explicit_probe: str | None) -> str:
    return explicit_probe or target.debug_probe or "stlink"


def cmd_inspect(args: argparse.Namespace) -> int:
    """打印工程摘要，用于第一阶段快速验证 parser 是否理解 Keil 工程。"""

    model = parse_uvprojx(args.project)
    target = _pick_target(model, args.target)

    print(f"Project: {model.project_file}")
    print(f"Project root: {model.inferred_project_root}")
    print(f"Target: {target.name}")
    print(f"Device: {target.device or '(unknown)'}")
    print(f"Vendor/family: {(target.vendor or 'unknown')}/{(target.family or 'unknown')}")
    print(f"Core: {target.core or '(unknown)'}")
    print(f"FPU/float ABI: {(target.fpu or 'none')}/{target.float_abi or 'unknown'}")
    print(f"Device database: {'matched' if target.device_info.matched else 'not matched'}")
    openocd_target = resolve_openocd_target(target)
    if openocd_target.target_cfg:
        print(f"OpenOCD target: {openocd_target.target_cfg} ({openocd_target.status})")
    print(f"CPU: {target.cpu or '(not specified)'}")
    if target.memory:
        memory = ", ".join(f"{region.name} {region.origin}+{region.length}" for region in target.memory)
        print(f"Memory: {memory}")
    print(f"C standard: {target.c_standard}")
    print(f"Sources: {len(target.sources)}")
    print(f"Includes: {len(target.includes)}")
    print(f"Defines: {len(target.defines)}")
    print(f"Libraries: {len(target.libraries)}")
    print(f"Startup files: {len(target.startup_files)}")
    print(f"Debug probe: {target.debug_probe or '(not inferred)'}")
    print(f"Keil debug DLL: {target.keil_debug_dll or '(unknown)'}")
    print(f"Flash algorithm: {target.flash_algorithm or '(unknown)'}")
    print(f"Scatter file: {target.scatter_file or '(none)'}")
    print(f"Scatter candidates: {len(target.scatter_candidates)}")
    print(f"Framework: {target.features.framework}")
    print(f"Generated by: {target.features.generated_by or '(unknown)'}")
    print(f"RTOS: {', '.join(target.features.rtos) if target.features.rtos else '(none detected)'}")
    print(f"Middleware: {', '.join(target.features.middleware) if target.features.middleware else '(none detected)'}")

    if args.verbose:
        print("\nDefines:")
        for item in target.defines:
            print(f"  {item}")
        print("\nSource groups:")
        groups: dict[str, int] = {}
        for source in target.sources:
            groups[source.group or "(ungrouped)"] = groups.get(source.group or "(ungrouped)", 0) + 1
        for group, count in sorted(groups.items()):
            print(f"  {group}: {count}")
        if target.scatter_candidates:
            print("\nScatter candidates:")
            for path in target.scatter_candidates:
                print(f"  {path}")
        if target.features.evidence:
            print("\nFeature evidence:")
            for item in target.features.evidence:
                print(f"  {item}")

    diagnostics = diagnose_target(target)
    if diagnostics:
        print("\nDiagnostics:")
        for diagnostic in diagnostics:
            print(f"  [{diagnostic.level}] {diagnostic.code}: {diagnostic.message}")
            if args.verbose and diagnostic.detail:
                print(f"    {diagnostic.detail}")

    return 0


def cmd_scatter(args: argparse.Namespace) -> int:
    """检查 Keil scatter，并可预览转换后的 GNU ld 脚本。"""

    model = parse_uvprojx(args.project)
    target = _pick_target(model, args.target)

    scatter_file = target.scatter_file
    if not scatter_file and target.scatter_candidates:
        scatter_file = target.scatter_candidates[0]
    if not scatter_file:
        raise SystemExit("No scatter file found. Memory can still be inferred from Cpu metadata, but there is no .sct to convert.")

    memory = parse_scatter_memory(scatter_file)
    print(f"Scatter: {scatter_file}")
    for region in memory:
        print(f"  {region.name}: {region.origin}+{region.length}")

    if args.emit_ld:
        print("\n# Generated GNU ld preview")
        print(generate_gnu_ld(memory))

    return 0


def cmd_model(args: argparse.Namespace) -> int:
    """输出 JSON 中间模型，方便后续测试和 generator 调试。"""

    model = parse_uvprojx(args.project)
    if args.target:
        target = _pick_target(model, args.target)
        payload = {
            "project_file": model.project_file,
            "keil_project_dir": model.keil_project_dir,
            "inferred_project_root": model.inferred_project_root,
            "target": asdict(target),
        }
    else:
        payload = model.to_dict()
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 0


def cmd_configure(args: argparse.Namespace) -> int:
    """生成 KeilBridge 外部 CMake/OpenOCD/VS Code 工作区。"""

    model = parse_uvprojx(args.project)
    target = _pick_target(model, args.target)
    workspace_root = Path(args.workspace_root).resolve() if args.workspace_root else Path(model.inferred_project_root)
    recommendation = _write_backend_report(workspace_root, target, args.armclang_root, None)
    _print_backend_summary(recommendation)

    if args.backend == "auto":
        print("Auto mode only writes the backend diagnosis. Re-run configure with --backend gcc, armclang, or debug-only after choosing.")
        return 0
    if args.backend == "armclang":
        probe = _resolve_probe(target, args.probe)
        generated_dir = configure_armclang_workspace(workspace_root, target, probe=probe, armclang_root=args.armclang_root)
        print(f"Generated ArmClang workspace: {generated_dir}")
        print("Next:")
        print(f"  python -m keiltool.cli build --project \"{model.project_file}\" --target {target.name} --backend armclang")
        return 0
    if args.backend == "debug-only":
        probe = _resolve_probe(target, args.probe)
        generated_dir = configure_debug_only_workspace(
            workspace_root,
            target,
            probe=probe,
            executable=args.elf,
            keil_project_dir=model.keil_project_dir,
        )
        print(f"Generated Debug-only workspace: {generated_dir}")
        print("Open:")
        print(f"  {workspace_root / '.keilbridge' / f'KeilBridge_{_sanitize_name(target.name)}_debug.code-workspace'}")
        return 0

    probe = _resolve_probe(target, args.probe)
    generated_dir = configure_workspace(workspace_root, target, probe=probe)
    print(f"Generated workspace: {generated_dir}")
    print("Next:")
    print(f"  python -m keiltool.cli build --project \"{model.project_file}\" --target {target.name}")
    return 0


def cmd_build(args: argparse.Namespace) -> int:
    """调用 CMake 构建已生成的外部工作区。"""

    generated_dir, build_dir = _resolve_build_dirs(args)
    cmake = find_cmake(args.cmake)
    ninja = find_ninja(args.ninja)
    env = dict(os.environ)
    arm_gcc_root = find_arm_gcc_root(args.arm_gcc_root) if args.backend == "gcc" else ""
    if arm_gcc_root:
        env["ARM_GCC_ROOT"] = arm_gcc_root
    if args.backend == "armclang":
        tools = find_armclang_tools(args.armclang_root)
        missing = [name for name, path in tools.items() if not path]
        if missing:
            raise SystemExit(
                "ArmClang tools not found: "
                + ", ".join(missing)
                + ". Install Keil MDK ArmClang/Arm Compiler 6, add ARMCLANG/bin to PATH, "
                + "or pass --armclang-root / set ARMCLANG_ROOT."
            )
        for key, value in armclang_environment(args.armclang_root).items():
            if key == "PATH_PREFIX":
                env["PATH"] = value + os.pathsep + env.get("PATH", "")
            else:
                env[key] = value

    _run([
        cmake,
        "-S",
        str(generated_dir),
        "-B",
        str(build_dir),
        "-G",
        "Ninja",
        f"-DCMAKE_MAKE_PROGRAM={ninja}",
    ], cwd=generated_dir, env=env)
    _run([cmake, "--build", str(build_dir)], cwd=generated_dir, env=env)
    return 0


def cmd_openocd(args: argparse.Namespace) -> int:
    """打印或启动 OpenOCD 调试服务。

    MVP 阶段默认只生成命令，不强制后台启动，避免用户硬件未连接时误卡住。
    """

    model = parse_uvprojx(args.project)
    target = _pick_target(model, args.target)
    probe = _resolve_probe(target, args.probe)
    interface = {
        "stlink": "interface/stlink.cfg",
        "cmsis-dap": "interface/cmsis-dap.cfg",
        "daplink": "interface/cmsis-dap.cfg",
    }.get(probe, "interface/stlink.cfg")
    openocd = find_openocd(args.openocd)
    scripts = find_openocd_scripts(openocd)
    target_resolution = resolve_openocd_target(target, scripts)
    if not target_resolution.target_cfg:
        raise SystemExit(f"OpenOCD target could not be resolved: {target_resolution.reason}")
    command = [openocd]
    if scripts:
        command.extend(["-s", scripts])
    command.extend(["-f", interface, "-f", target_resolution.target_cfg])
    print(" ".join(command))
    if args.run:
        _run(command, cwd=Path.cwd())
    return 0


def cmd_flash(args: argparse.Namespace) -> int:
    """通过 ST-Link/OpenOCD 下载现有 HEX 或 BIN 固件。

    `doctor flash` 只做连接/复位/向量表诊断，不应该承担真正下载职责。
    这里提供明确的 flash 命令，内部调用 OpenOCD `program <firmware> verify reset exit`，
    成功标准就是 OpenOCD 返回 0 且输出 program/verify 通过。
    """

    model = parse_uvprojx(args.project)
    target = _pick_target(model, args.target)
    probe = _resolve_probe(target, args.probe)
    workspace_root = Path(args.workspace_root).resolve() if args.workspace_root else Path(model.inferred_project_root)
    project_name = _sanitize_name(target.name)
    generated_dir = workspace_root / ".keilbridge" / "generated"
    firmware_arg = getattr(args, "firmware", None)
    elf_arg = getattr(args, "elf", None)
    openocd = find_openocd(args.openocd)
    scripts = find_openocd_scripts(openocd)

    if firmware_arg is None:
        cfg = generated_dir / "openocd" / f"{project_name}_{probe}.cfg"
        build_dir = workspace_root / ".keilbridge" / "build" / "gcc-debug"
        firmware = Path(elf_arg).resolve() if elf_arg else build_dir / f"{project_name}.elf"
        if not cfg.exists():
            raise SystemExit(f"OpenOCD config not found: {cfg}. Run configure first.")
        if not firmware.exists():
            raise SystemExit(f"ELF not found: {firmware}. Run build first.")
        config = OpenOcdConfig(
            executable=Path(openocd),
            scripts_dir=Path(scripts) if scripts else None,
            interface_cfg=None,
            target_cfg=str(cfg),
        )
        cwd = generated_dir
    else:
        if probe != "stlink":
            raise SystemExit("HEX/BIN flash supports only the ST-Link OpenOCD probe.")
        target_resolution = resolve_openocd_target(target, scripts)
        if not target_resolution.target_cfg or not target_resolution.status.endswith("_verified"):
            raise SystemExit(f"OpenOCD target could not be resolved: {target_resolution.reason}")
        firmware = Path(firmware_arg).resolve()
        config = OpenOcdConfig(
            executable=Path(openocd),
            scripts_dir=Path(scripts) if scripts else None,
            interface_cfg="interface/stlink.cfg",
            target_cfg=target_resolution.target_cfg,
        )
        cwd = workspace_root

    request = FlashRequest(firmware=firmware, base_address=args.base_address)
    logs_dir = workspace_root / ".keilbridge" / "logs"
    try:
        result = run_flash(
            config,
            request,
            logs_dir,
            cwd=cwd,
            target=target,
            target_name=target.name,
        )
    except ValueError as exc:
        raise SystemExit(str(exc)) from exc
    print(" ".join(f'"{item}"' if " " in item else item for item in result.command))
    if result.stdout:
        print(result.stdout, end="")
    if result.stderr:
        print(result.stderr, end="")
    print(f"Flash logs: {result.stdout_log} ; {result.stderr_log}")
    if not result.success:
        if result.findings:
            print("KeilBridge Flash Doctor:")
            for finding in result.findings:
                print(f"[{finding.severity}] {finding.code}: {finding.title}")
                if finding.evidence:
                    print(f"  evidence: {finding.evidence}")
                if finding.suggestion:
                    print(f"  suggestion: {finding.suggestion}")
        return result.returncode or 1
    return 0


def cmd_doctor_flash(args: argparse.Namespace) -> int:
    """诊断 OpenOCD/探针/烧录链路。

    第一版 Flash Doctor 专门解决用户最常见的“VS Code 只弹 GDB Server Quit
    Unexpectedly，但不知道 OpenOCD 真正哪里坏了”的问题。默认分析已有日志；
    `--run` 才主动启动 OpenOCD，避免无意中占用或复位用户硬件。
    """

    model = parse_uvprojx(args.project)
    target = _pick_target(model, args.target)
    probe = _resolve_probe(target, args.probe)
    workspace_root = Path(args.workspace_root).resolve() if args.workspace_root else Path(model.inferred_project_root)
    result = run_flash_doctor(
        target=target,
        workspace_root=workspace_root,
        probe=probe,
        openocd_path=args.openocd,
        run_probe=args.run,
    )
    report_dir = workspace_root / ".keilbridge" / "generated" / "reports"
    report_dir.mkdir(parents=True, exist_ok=True)
    json_path = report_dir / "flash_doctor_result.json"
    md_path = report_dir / "flash_doctor_report.md"
    json_path.write_text(json.dumps(result.to_dict(), ensure_ascii=False, indent=2), encoding="utf-8", newline="\n")
    md_path.write_text(render_flash_doctor_markdown(result, target, probe), encoding="utf-8", newline="\n")

    print(f"Flash Doctor report: {md_path}")
    for finding in result.findings:
        print(f"[{finding.severity}] {finding.code}: {finding.title}")
        if finding.evidence:
            print(f"  evidence: {finding.evidence}")
        if finding.suggestion:
            print(f"  suggestion: {finding.suggestion}")
    return 1 if any(item.severity in {"fail", "fatal"} for item in result.findings) else 0


def cmd_doctor_backend(args: argparse.Namespace) -> int:
    """诊断当前 Keil target 适合走哪条后端路线。"""

    model = parse_uvprojx(args.project)
    target = _pick_target(model, args.target)
    workspace_root = Path(args.workspace_root).resolve() if args.workspace_root else Path(model.inferred_project_root)
    result = _write_backend_report(workspace_root, target, args.armclang_root, args.arm_gcc_root)
    print(f"Backend Doctor report: {workspace_root / '.keilbridge' / 'generated' / 'reports' / 'backend_recommendation.md'}")
    _print_backend_summary(result)
    return 1 if any(item.status == "blocked" for item in result.options if item.backend == result.recommended) else 0


def cmd_doctor_elf(args: argparse.Namespace) -> int:
    """诊断已经构建出来的 ELF 是否存在启动/链接语义风险。"""

    model = parse_uvprojx(args.project)
    target = _pick_target(model, args.target)
    workspace_root = Path(args.workspace_root).resolve() if args.workspace_root else Path(model.inferred_project_root)
    result = run_elf_doctor(
        target=target,
        workspace_root=workspace_root,
        elf=Path(args.elf).resolve() if args.elf else None,
        arm_gcc_root=args.arm_gcc_root,
    )
    report_dir = workspace_root / ".keilbridge" / "generated" / "reports"
    report_dir.mkdir(parents=True, exist_ok=True)
    json_path = report_dir / "elf_doctor_result.json"
    md_path = report_dir / "elf_doctor_report.md"
    json_path.write_text(json.dumps(result.to_dict(), ensure_ascii=False, indent=2), encoding="utf-8", newline="\n")
    md_path.write_text(render_elf_doctor_markdown(result), encoding="utf-8", newline="\n")

    print(f"ELF Doctor report: {md_path}")
    for finding in result.findings:
        print(f"[{finding.severity}] {finding.code}: {finding.title}")
        if finding.evidence:
            print(f"  evidence: {finding.evidence}")
        if finding.suggestion:
            print(f"  suggestion: {finding.suggestion}")
    return 1 if any(item.severity in {"fail", "fatal"} for item in result.findings) else 0


def cmd_keil(args: argparse.Namespace) -> int:
    """Call Keil uVision command line for build/rebuild/download fallback workflows."""

    model = parse_uvprojx(args.project)
    target = _pick_target(model, args.target)
    workspace_root = Path(args.workspace_root).resolve() if args.workspace_root else Path(model.inferred_project_root)
    try:
        result = run_keil_cli(
            project=Path(model.project_file),
            target=target.name,
            action=args.keil_command,
            uvision=args.uvision,
            workspace_root=workspace_root,
        )
    except FileNotFoundError as exc:
        raise SystemExit(str(exc)) from exc
    print(" ".join(f'"{item}"' if " " in item else item for item in result.command))
    print(f"Keil {args.keil_command} mode: {result.mode}")
    print(f"Keil {args.keil_command} log: {result.log_path}")
    return result.returncode


def cmd_gui(args: argparse.Namespace) -> int:
    from .gui import launch_gui

    launch_gui()
    return 0


def _write_backend_report(workspace_root: Path, target, armclang_root: str | None, arm_gcc_root: str | None):
    """写入后端推荐报告，供首次配置和独立 Doctor 共用。"""

    result = recommend_backends(target, armclang_root=armclang_root, arm_gcc_root=arm_gcc_root)
    report_dir = workspace_root / ".keilbridge" / "generated" / "reports"
    report_dir.mkdir(parents=True, exist_ok=True)
    (report_dir / "backend_recommendation.json").write_text(
        json.dumps(result.to_dict(), ensure_ascii=False, indent=2),
        encoding="utf-8",
        newline="\n",
    )
    (report_dir / "backend_recommendation.md").write_text(
        render_backend_recommendation_markdown(result, target),
        encoding="utf-8",
        newline="\n",
    )
    return result


def _print_backend_summary(result) -> None:
    print(f"Recommended backend: {result.recommended}")
    for option in result.options:
        print(f"  [{option.status}] {option.backend}: {option.title}")
        if option.blockers:
            print(f"    blockers: {'; '.join(option.blockers)}")


def _run(command: list[str], cwd: Path, env: dict[str, str] | None = None) -> None:
    try:
        subprocess.run(command, cwd=cwd, env=env, check=True)
    except FileNotFoundError as exc:
        raise SystemExit(f"Command not found: {command[0]}. Please install it or pass an explicit path.") from exc
    except subprocess.CalledProcessError as exc:
        raise SystemExit(exc.returncode) from exc


def _resolve_build_dirs(args: argparse.Namespace) -> tuple[Path, Path]:
    """解析 build 使用的 generated/build 目录。

    推荐传入 `--project/--target`，这样 build 会自动使用目标工程根目录下的
    `.keilbridge`。不传 project 时保留旧行为，使用当前目录下的 `.keilbridge`。
    """

    if args.project:
        model = parse_uvprojx(args.project)
        _pick_target(model, args.target)
        workspace_root = Path(args.workspace_root).resolve() if args.workspace_root else Path(model.inferred_project_root)
        if args.backend == "armclang":
            return (
                workspace_root / ".keilbridge" / "generated" / "armclang",
                workspace_root / ".keilbridge" / "build" / "armclang-debug",
            )
        return (
            workspace_root / ".keilbridge" / "generated",
            workspace_root / ".keilbridge" / "build" / "gcc-debug",
        )

    generated_dir = Path(args.generated_dir).resolve()
    build_dir = Path(args.build_dir).resolve()
    return generated_dir, build_dir


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="k2c", description="Keil external CMake adapter")
    subparsers = parser.add_subparsers(dest="command", required=True)

    inspect_parser = subparsers.add_parser("inspect", help="Print a Keil project summary")
    inspect_parser.add_argument("project", type=Path, help="Path to .uvprojx")
    inspect_parser.add_argument("--target", help="Keil target name")
    inspect_parser.add_argument("-v", "--verbose", action="store_true", help="Print additional details")
    inspect_parser.set_defaults(func=cmd_inspect)

    model_parser = subparsers.add_parser("model", help="Print normalized JSON model")
    model_parser.add_argument("project", type=Path, help="Path to .uvprojx")
    model_parser.add_argument("--target", help="Keil target name")
    model_parser.set_defaults(func=cmd_model)

    scatter_parser = subparsers.add_parser("scatter", help="Inspect or convert Keil scatter file")
    scatter_parser.add_argument("project", type=Path, help="Path to .uvprojx")
    scatter_parser.add_argument("--target", help="Keil target name")
    scatter_parser.add_argument("--emit-ld", action="store_true", help="Print GNU ld script preview")
    scatter_parser.set_defaults(func=cmd_scatter)

    configure_parser = subparsers.add_parser("configure", help="Generate external CMake/OpenOCD workspace")
    configure_parser.add_argument("--project", required=True, type=Path, help="Path to .uvprojx")
    configure_parser.add_argument("--target", help="Keil target name")
    configure_parser.add_argument("--probe", help="Probe profile: stlink, cmsis-dap, daplink. Defaults to uvoptx inference, then stlink.")
    configure_parser.add_argument("--workspace-root", help="Override .keilbridge location; defaults to inferred Keil project root")
    configure_parser.add_argument("--backend", choices=["auto", "gcc", "armclang", "debug-only"], default="auto", help="Build backend. Default auto writes recommendation only.")
    configure_parser.add_argument("--armclang-root", help="Path to ArmClang/Keil ARMCLANG root or bin directory")
    configure_parser.add_argument("--elf", help="Existing AXF/ELF for debug-only backend")
    configure_parser.set_defaults(func=cmd_configure)

    build_cmd = subparsers.add_parser("build", help="Build generated CMake workspace")
    build_cmd.add_argument("--project", type=Path, help="Path to .uvprojx; enables per-project .keilbridge lookup")
    build_cmd.add_argument("--target", help="Keil target name")
    build_cmd.add_argument("--workspace-root", help="Override .keilbridge location; defaults to inferred Keil project root")
    build_cmd.add_argument("--generated-dir", default=".keilbridge/generated", help="Generated workspace directory")
    build_cmd.add_argument("--build-dir", default=".keilbridge/build/gcc-debug", help="CMake build directory")
    build_cmd.add_argument("--backend", choices=["gcc", "armclang"], default="gcc", help="Build backend to use")
    build_cmd.add_argument("--cmake", help="Path to cmake executable")
    build_cmd.add_argument("--ninja", help="Path to ninja executable")
    build_cmd.add_argument("--arm-gcc-root", help="Path to Arm GNU Toolchain root")
    build_cmd.add_argument("--armclang-root", help="Path to ArmClang/Keil ARMCLANG root or bin directory")
    build_cmd.set_defaults(func=cmd_build)

    openocd_cmd = subparsers.add_parser("openocd", help="Print or run OpenOCD debug server command")
    openocd_cmd.add_argument("--project", required=True, type=Path, help="Path to .uvprojx")
    openocd_cmd.add_argument("--target", help="Keil target name")
    openocd_cmd.add_argument("--probe", help="Probe profile: stlink, cmsis-dap, daplink. Defaults to uvoptx inference, then stlink.")
    openocd_cmd.add_argument("--openocd", help="Path to openocd executable")
    openocd_cmd.add_argument("--run", action="store_true", help="Run OpenOCD instead of only printing the command")
    openocd_cmd.set_defaults(func=cmd_openocd)

    flash_cmd = subparsers.add_parser("flash", help="Program the generated ELF or an existing HEX/BIN file with OpenOCD")
    flash_cmd.add_argument("--project", required=True, type=Path, help="Path to .uvprojx")
    flash_cmd.add_argument("--target", help="Keil target name")
    flash_cmd.add_argument("--probe", help="Probe profile for legacy generated ELF; HEX/BIN supports ST-Link.")
    flash_cmd.add_argument("--workspace-root", help="Override .keilbridge location; defaults to inferred Keil project root")
    flash_cmd.add_argument("--openocd", help="Path to openocd executable")
    image_group = flash_cmd.add_mutually_exclusive_group()
    image_group.add_argument("--elf", type=Path, help="Override ELF path; defaults to .keilbridge/build/gcc-debug/<target>.elf")
    image_group.add_argument("--firmware", type=Path, help="Existing .hex or .bin firmware file")
    flash_cmd.add_argument("--base-address", type=parse_address, default=0x08000000, help="BIN flash base address (default: 0x08000000)")
    flash_cmd.set_defaults(func=cmd_flash)

    gui_cmd = subparsers.add_parser("gui", help="Launch the ST-Link flash and RTT workbench")
    gui_cmd.set_defaults(func=cmd_gui)

    doctor_parser = subparsers.add_parser("doctor", help="Run KeilBridge staged diagnostics")
    doctor_subparsers = doctor_parser.add_subparsers(dest="doctor_command", required=True)

    doctor_flash = doctor_subparsers.add_parser("flash", help="Diagnose OpenOCD/probe/flash connection")
    doctor_flash.add_argument("--project", required=True, type=Path, help="Path to .uvprojx")
    doctor_flash.add_argument("--target", help="Keil target name")
    doctor_flash.add_argument("--probe", help="Probe profile: stlink, cmsis-dap, daplink. Defaults to uvoptx inference, then stlink.")
    doctor_flash.add_argument("--workspace-root", help="Override .keilbridge location; defaults to inferred Keil project root")
    doctor_flash.add_argument("--openocd", help="Path to openocd executable")
    doctor_flash.add_argument("--run", action="store_true", help="Run a minimal OpenOCD connect/reset/vector read test")
    doctor_flash.set_defaults(func=cmd_doctor_flash)

    doctor_backend = doctor_subparsers.add_parser("backend", help="Recommend GCC, ArmClang, Debug-only, or Keil CLI backend")
    doctor_backend.add_argument("--project", required=True, type=Path, help="Path to .uvprojx")
    doctor_backend.add_argument("--target", help="Keil target name")
    doctor_backend.add_argument("--workspace-root", help="Override .keilbridge location; defaults to inferred Keil project root")
    doctor_backend.add_argument("--armclang-root", help="Path to ArmClang/Keil ARMCLANG root or bin directory")
    doctor_backend.add_argument("--arm-gcc-root", help="Path to Arm GNU Toolchain root")
    doctor_backend.set_defaults(func=cmd_doctor_backend)

    doctor_elf = doctor_subparsers.add_parser("elf", help="Diagnose generated ELF startup/linker semantics")
    doctor_elf.add_argument("--project", required=True, type=Path, help="Path to .uvprojx")
    doctor_elf.add_argument("--target", help="Keil target name")
    doctor_elf.add_argument("--workspace-root", help="Override .keilbridge location; defaults to inferred Keil project root")
    doctor_elf.add_argument("--elf", help="Override ELF path; defaults to .keilbridge/build/gcc-debug/<target>.elf")
    doctor_elf.add_argument("--arm-gcc-root", help="Path to Arm GNU Toolchain root")
    doctor_elf.set_defaults(func=cmd_doctor_elf)

    keil_parser = subparsers.add_parser("keil", help="Run Keil uVision CLI build/rebuild/download")
    keil_subparsers = keil_parser.add_subparsers(dest="keil_command", required=True)
    for name, help_text in {
        "build": "Build the selected Keil target with uVision CLI",
        "rebuild": "Rebuild the selected Keil target with uVision CLI",
        "download": "Program Flash with the selected Keil target settings",
    }.items():
        cmd = keil_subparsers.add_parser(name, help=help_text)
        cmd.add_argument("--project", required=True, type=Path, help="Path to .uvprojx")
        cmd.add_argument("--target", help="Keil target name")
        cmd.add_argument("--workspace-root", help="Override .keilbridge location; defaults to inferred Keil project root")
        cmd.add_argument("--uvision", help="Path to UV4.exe/UV4.com. Defaults to PATH and common Keil install paths.")
        cmd.set_defaults(func=cmd_keil)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
