from __future__ import annotations

import argparse
import json
import os
import subprocess
from dataclasses import asdict
from pathlib import Path

from .core.diagnostics import diagnose_target
from .core.keil_parser import parse_uvprojx
from .core.scatter import generate_gnu_ld, parse_scatter_memory
from .core.tool_finder import find_arm_gcc_root, find_cmake, find_ninja, find_openocd
from .core.workspace import configure_workspace


def _pick_target(model, target_name: str | None):
    """选择 Keil Target。

    不指定 target 时沿用 Keil 文件中的第一个 Target，后续可以改成读取 uvoptx
    的当前活动 target。
    """

    if not model.targets:
        raise SystemExit("No targets found in Keil project.")
    if target_name is None:
        return model.targets[0]
    for target in model.targets:
        if target.name == target_name:
            return target
    names = ", ".join(target.name for target in model.targets)
    raise SystemExit(f"Target not found: {target_name}. Available targets: {names}")


def cmd_inspect(args: argparse.Namespace) -> int:
    """打印工程摘要，用于第一阶段快速验证 parser 是否理解 Keil 工程。"""

    model = parse_uvprojx(args.project)
    target = _pick_target(model, args.target)

    print(f"Project: {model.project_file}")
    print(f"Project root: {model.inferred_project_root}")
    print(f"Target: {target.name}")
    print(f"Device: {target.device or '(unknown)'}")
    print(f"Vendor/family: {(target.vendor or 'unknown')}/{(target.family or 'unknown')}")
    print(f"Core: {target.core or '(unknown)'}")
    print(f"FPU/float ABI: {(target.fpu or 'none')}/{target.float_abi or 'unknown'}")
    print(f"Device database: {'matched' if target.device_info.matched else 'not matched'}")
    if target.device_info.openocd_target:
        print(f"OpenOCD target: {target.device_info.openocd_target}")
    print(f"CPU: {target.cpu or '(not specified)'}")
    if target.memory:
        memory = ", ".join(f"{region.name} {region.origin}+{region.length}" for region in target.memory)
        print(f"Memory: {memory}")
    print(f"C standard: {target.c_standard}")
    print(f"Sources: {len(target.sources)}")
    print(f"Includes: {len(target.includes)}")
    print(f"Defines: {len(target.defines)}")
    print(f"Libraries: {len(target.libraries)}")
    print(f"Startup files: {len(target.startup_files)}")
    print(f"Scatter file: {target.scatter_file or '(none)'}")
    print(f"Scatter candidates: {len(target.scatter_candidates)}")
    print(f"Framework: {target.features.framework}")
    print(f"Generated by: {target.features.generated_by or '(unknown)'}")
    print(f"RTOS: {', '.join(target.features.rtos) if target.features.rtos else '(none detected)'}")
    print(f"Middleware: {', '.join(target.features.middleware) if target.features.middleware else '(none detected)'}")

    if args.verbose:
        print("\nDefines:")
        for item in target.defines:
            print(f"  {item}")
        print("\nSource groups:")
        groups: dict[str, int] = {}
        for source in target.sources:
            groups[source.group or "(ungrouped)"] = groups.get(source.group or "(ungrouped)", 0) + 1
        for group, count in sorted(groups.items()):
            print(f"  {group}: {count}")
        if target.scatter_candidates:
            print("\nScatter candidates:")
            for path in target.scatter_candidates:
                print(f"  {path}")
        if target.features.evidence:
            print("\nFeature evidence:")
            for item in target.features.evidence:
                print(f"  {item}")

    diagnostics = diagnose_target(target)
    if diagnostics:
        print("\nDiagnostics:")
        for diagnostic in diagnostics:
            print(f"  [{diagnostic.level}] {diagnostic.code}: {diagnostic.message}")
            if args.verbose and diagnostic.detail:
                print(f"    {diagnostic.detail}")

    return 0


def cmd_scatter(args: argparse.Namespace) -> int:
    """检查 Keil scatter，并可预览转换后的 GNU ld 脚本。"""

    model = parse_uvprojx(args.project)
    target = _pick_target(model, args.target)

    scatter_file = target.scatter_file
    if not scatter_file and target.scatter_candidates:
        scatter_file = target.scatter_candidates[0]
    if not scatter_file:
        raise SystemExit("No scatter file found. Memory can still be inferred from Cpu metadata, but there is no .sct to convert.")

    memory = parse_scatter_memory(scatter_file)
    print(f"Scatter: {scatter_file}")
    for region in memory:
        print(f"  {region.name}: {region.origin}+{region.length}")

    if args.emit_ld:
        print("\n# Generated GNU ld preview")
        print(generate_gnu_ld(memory))

    return 0


def cmd_model(args: argparse.Namespace) -> int:
    """输出 JSON 中间模型，方便后续测试和 generator 调试。"""

    model = parse_uvprojx(args.project)
    if args.target:
        target = _pick_target(model, args.target)
        payload = {
            "project_file": model.project_file,
            "keil_project_dir": model.keil_project_dir,
            "inferred_project_root": model.inferred_project_root,
            "target": asdict(target),
        }
    else:
        payload = model.to_dict()
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 0


def cmd_configure(args: argparse.Namespace) -> int:
    """生成 KeilBridge 外部 CMake/OpenOCD/VS Code 工作区。"""

    model = parse_uvprojx(args.project)
    target = _pick_target(model, args.target)
    workspace_root = Path(args.workspace_root).resolve() if args.workspace_root else Path(model.inferred_project_root)
    generated_dir = configure_workspace(workspace_root, target, probe=args.probe)
    print(f"Generated workspace: {generated_dir}")
    print("Next:")
    print(f"  python -m keiltool.cli build --project \"{model.project_file}\" --target {target.name}")
    return 0


def cmd_build(args: argparse.Namespace) -> int:
    """调用 CMake 构建已生成的外部工作区。"""

    generated_dir, build_dir = _resolve_build_dirs(args)
    cmake = find_cmake(args.cmake)
    ninja = find_ninja(args.ninja)
    env = dict(os.environ)
    arm_gcc_root = find_arm_gcc_root(args.arm_gcc_root)
    if arm_gcc_root:
        env["ARM_GCC_ROOT"] = arm_gcc_root

    _run([
        cmake,
        "-S",
        str(generated_dir),
        "-B",
        str(build_dir),
        "-G",
        "Ninja",
        f"-DCMAKE_MAKE_PROGRAM={ninja}",
    ], cwd=generated_dir, env=env)
    _run([cmake, "--build", str(build_dir)], cwd=generated_dir, env=env)
    return 0


def cmd_openocd(args: argparse.Namespace) -> int:
    """打印或启动 OpenOCD 调试服务。

    MVP 阶段默认只生成命令，不强制后台启动，避免用户硬件未连接时误卡住。
    """

    model = parse_uvprojx(args.project)
    target = _pick_target(model, args.target)
    interface = {
        "stlink": "interface/stlink.cfg",
        "cmsis-dap": "interface/cmsis-dap.cfg",
        "daplink": "interface/cmsis-dap.cfg",
    }.get(args.probe, "interface/stlink.cfg")
    target_cfg = target.device_info.openocd_target or f"target/{target.family}x.cfg"
    openocd = find_openocd(args.openocd)
    command = [openocd, "-f", interface, "-f", target_cfg]
    print(" ".join(command))
    if args.run:
        _run(command, cwd=Path.cwd())
    return 0


def _run(command: list[str], cwd: Path, env: dict[str, str] | None = None) -> None:
    try:
        subprocess.run(command, cwd=cwd, env=env, check=True)
    except FileNotFoundError as exc:
        raise SystemExit(f"Command not found: {command[0]}. Please install it or pass an explicit path.") from exc
    except subprocess.CalledProcessError as exc:
        raise SystemExit(exc.returncode) from exc


def _resolve_build_dirs(args: argparse.Namespace) -> tuple[Path, Path]:
    """解析 build 使用的 generated/build 目录。

    推荐传入 `--project/--target`，这样 build 会自动使用目标工程根目录下的
    `.keilbridge`。不传 project 时保留旧行为，使用当前目录下的 `.keilbridge`。
    """

    if args.project:
        model = parse_uvprojx(args.project)
        _pick_target(model, args.target)
        workspace_root = Path(args.workspace_root).resolve() if args.workspace_root else Path(model.inferred_project_root)
        return (
            workspace_root / ".keilbridge" / "generated",
            workspace_root / ".keilbridge" / "build" / "gcc-debug",
        )

    generated_dir = Path(args.generated_dir).resolve()
    build_dir = Path(args.build_dir).resolve()
    return generated_dir, build_dir


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="k2c", description="Keil external CMake adapter")
    subparsers = parser.add_subparsers(dest="command", required=True)

    inspect_parser = subparsers.add_parser("inspect", help="Print a Keil project summary")
    inspect_parser.add_argument("project", type=Path, help="Path to .uvprojx")
    inspect_parser.add_argument("--target", help="Keil target name")
    inspect_parser.add_argument("-v", "--verbose", action="store_true", help="Print additional details")
    inspect_parser.set_defaults(func=cmd_inspect)

    model_parser = subparsers.add_parser("model", help="Print normalized JSON model")
    model_parser.add_argument("project", type=Path, help="Path to .uvprojx")
    model_parser.add_argument("--target", help="Keil target name")
    model_parser.set_defaults(func=cmd_model)

    scatter_parser = subparsers.add_parser("scatter", help="Inspect or convert Keil scatter file")
    scatter_parser.add_argument("project", type=Path, help="Path to .uvprojx")
    scatter_parser.add_argument("--target", help="Keil target name")
    scatter_parser.add_argument("--emit-ld", action="store_true", help="Print GNU ld script preview")
    scatter_parser.set_defaults(func=cmd_scatter)

    configure_parser = subparsers.add_parser("configure", help="Generate external CMake/OpenOCD workspace")
    configure_parser.add_argument("--project", required=True, type=Path, help="Path to .uvprojx")
    configure_parser.add_argument("--target", help="Keil target name")
    configure_parser.add_argument("--probe", default="stlink", help="Probe profile: stlink, cmsis-dap, daplink")
    configure_parser.add_argument("--workspace-root", help="Override .keilbridge location; defaults to inferred Keil project root")
    configure_parser.set_defaults(func=cmd_configure)

    build_cmd = subparsers.add_parser("build", help="Build generated CMake workspace")
    build_cmd.add_argument("--project", type=Path, help="Path to .uvprojx; enables per-project .keilbridge lookup")
    build_cmd.add_argument("--target", help="Keil target name")
    build_cmd.add_argument("--workspace-root", help="Override .keilbridge location; defaults to inferred Keil project root")
    build_cmd.add_argument("--generated-dir", default=".keilbridge/generated", help="Generated workspace directory")
    build_cmd.add_argument("--build-dir", default=".keilbridge/build/gcc-debug", help="CMake build directory")
    build_cmd.add_argument("--cmake", help="Path to cmake executable")
    build_cmd.add_argument("--ninja", help="Path to ninja executable")
    build_cmd.add_argument("--arm-gcc-root", help="Path to Arm GNU Toolchain root")
    build_cmd.set_defaults(func=cmd_build)

    openocd_cmd = subparsers.add_parser("openocd", help="Print or run OpenOCD debug server command")
    openocd_cmd.add_argument("--project", required=True, type=Path, help="Path to .uvprojx")
    openocd_cmd.add_argument("--target", help="Keil target name")
    openocd_cmd.add_argument("--probe", default="stlink", help="Probe profile: stlink, cmsis-dap, daplink")
    openocd_cmd.add_argument("--openocd", help="Path to openocd executable")
    openocd_cmd.add_argument("--run", action="store_true", help="Run OpenOCD instead of only printing the command")
    openocd_cmd.set_defaults(func=cmd_openocd)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
